export default {
  seasonId: 20242025,
  gameTypeId: 2,
  playerStatsSeasons: [
    {
      season: 20242025,
      gameTypes: [2],
    },
    {
      season: 20232024,
      gameTypes: [2, 3],
    },
    {
      season: 20222023,
      gameTypes: [2, 3],
    },
    {
      season: 20212022,
      gameTypes: [2],
    },
    {
      season: 20202021,
      gameTypes: [2, 3],
    },
    {
      season: 20192020,
      gameTypes: [2, 3],
    },
    {
      season: 20182019,
      gameTypes: [2, 3],
    },
    {
      season: 20172018,
      gameTypes: [2, 3],
    },
    {
      season: 20162017,
      gameTypes: [2],
    },
    {
      season: 20152016,
      gameTypes: [2],
    },
  ],
  gameLog: [
    {
      gameId: 2024020747,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2025-01-20",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Utah Hockey Club",
        fr: "Club de hockey de l'Utah",
      },
      gamesStarted: 1,
      decision: "L",
      shotsAgainst: 27,
      goalsAgainst: 4,
      savePctg: 0.851852,
      shutouts: 0,
      opponentAbbrev: "UTA",
      pim: 0,
      toi: "59:24",
    },
    {
      gameId: 2024020716,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2025-01-16",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Kraken",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 18,
      goalsAgainst: 1,
      savePctg: 0.944444,
      shutouts: 0,
      opponentAbbrev: "SEA",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020702,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2025-01-14",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Canucks",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 24,
      goalsAgainst: 1,
      savePctg: 0.958333,
      shutouts: 0,
      opponentAbbrev: "VAN",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020678,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2025-01-11",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Avalanche",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 22,
      goalsAgainst: 0,
      savePctg: 1,
      shutouts: 1,
      opponentAbbrev: "COL",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020647,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2025-01-07",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Predators",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 28,
      goalsAgainst: 2,
      savePctg: 0.928571,
      shutouts: 0,
      opponentAbbrev: "NSH",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020621,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2025-01-04",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Red Wings",
      },
      gamesStarted: 1,
      decision: "L",
      shotsAgainst: 28,
      goalsAgainst: 3,
      savePctg: 0.892857,
      shutouts: 0,
      opponentAbbrev: "DET",
      pim: 0,
      toi: "57:53",
    },
    {
      gameId: 2024020609,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2025-01-02",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Ducks",
      },
      gamesStarted: 1,
      decision: "O",
      shotsAgainst: 24,
      goalsAgainst: 4,
      savePctg: 0.833333,
      shutouts: 0,
      opponentAbbrev: "ANA",
      pim: 0,
      toi: "63:34",
    },
    {
      gameId: 2024020587,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-12-30",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Predators",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 22,
      goalsAgainst: 0,
      savePctg: 1,
      shutouts: 1,
      opponentAbbrev: "NSH",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020574,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-12-28",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Senators",
        fr: "Sénateurs",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 35,
      goalsAgainst: 2,
      savePctg: 0.942857,
      shutouts: 0,
      opponentAbbrev: "OTT",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020546,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-12-23",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Maple Leafs",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 25,
      goalsAgainst: 2,
      savePctg: 0.92,
      shutouts: 0,
      opponentAbbrev: "TOR",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020536,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-12-21",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Wild",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 19,
      goalsAgainst: 0,
      savePctg: 1,
      shutouts: 1,
      opponentAbbrev: "MIN",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020506,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-12-17",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Sharks",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 35,
      goalsAgainst: 3,
      savePctg: 0.914286,
      shutouts: 0,
      opponentAbbrev: "SJS",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020482,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-12-14",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Canadiens",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 28,
      goalsAgainst: 2,
      savePctg: 0.928571,
      shutouts: 0,
      opponentAbbrev: "MTL",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020468,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-12-12",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Golden Knights",
      },
      gamesStarted: 1,
      decision: "O",
      shotsAgainst: 36,
      goalsAgainst: 3,
      savePctg: 0.916667,
      shutouts: 0,
      opponentAbbrev: "VGK",
      pim: 0,
      toi: "63:47",
    },
    {
      gameId: 2024020452,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-12-10",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Bruins",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 24,
      goalsAgainst: 1,
      savePctg: 0.958333,
      shutouts: 0,
      opponentAbbrev: "BOS",
      pim: 0,
      toi: "59:46",
    },
    {
      gameId: 2024020427,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-12-07",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Blackhawks",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 14,
      goalsAgainst: 2,
      savePctg: 0.857143,
      shutouts: 0,
      opponentAbbrev: "CHI",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020410,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-12-05",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Sabres",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 30,
      goalsAgainst: 2,
      savePctg: 0.933333,
      shutouts: 0,
      opponentAbbrev: "BUF",
      pim: 0,
      toi: "63:49",
    },
    {
      gameId: 2024020403,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-12-03",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Blues",
      },
      gamesStarted: 1,
      decision: "L",
      shotsAgainst: 31,
      goalsAgainst: 3,
      savePctg: 0.903226,
      shutouts: 0,
      opponentAbbrev: "STL",
      pim: 0,
      toi: "59:07",
    },
    {
      gameId: 2024020391,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-12-01",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Stars",
      },
      gamesStarted: 1,
      decision: "L",
      shotsAgainst: 30,
      goalsAgainst: 2,
      savePctg: 0.933333,
      shutouts: 0,
      opponentAbbrev: "DAL",
      pim: 0,
      toi: "58:22",
    },
    {
      gameId: 2024020359,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-11-27",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Kings",
      },
      gamesStarted: 1,
      decision: "L",
      shotsAgainst: 32,
      goalsAgainst: 3,
      savePctg: 0.90625,
      shutouts: 0,
      opponentAbbrev: "LAK",
      pim: 0,
      toi: "59:34",
    },
    {
      gameId: 2024020342,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-11-25",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Wild",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 44,
      goalsAgainst: 1,
      savePctg: 0.977273,
      shutouts: 0,
      opponentAbbrev: "MIN",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020316,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-11-22",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Penguins",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 18,
      goalsAgainst: 1,
      savePctg: 0.944444,
      shutouts: 0,
      opponentAbbrev: "PIT",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020297,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-11-19",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Panthers",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 23,
      goalsAgainst: 3,
      savePctg: 0.869565,
      shutouts: 0,
      opponentAbbrev: "FLA",
      pim: 0,
      toi: "59:54",
    },
    {
      gameId: 2024020277,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-11-16",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Panthers",
      },
      gamesStarted: 1,
      decision: "L",
      shotsAgainst: 31,
      goalsAgainst: 5,
      savePctg: 0.83871,
      shutouts: 0,
      opponentAbbrev: "FLA",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020247,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-11-12",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Rangers",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 36,
      goalsAgainst: 3,
      savePctg: 0.916667,
      shutouts: 0,
      opponentAbbrev: "NYR",
      pim: 0,
      toi: "59:59",
    },
    {
      gameId: 2024020230,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-11-09",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Stars",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 33,
      goalsAgainst: 1,
      savePctg: 0.969697,
      shutouts: 0,
      opponentAbbrev: "DAL",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020217,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-11-07",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Avalanche",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 35,
      goalsAgainst: 0,
      savePctg: 1,
      shutouts: 1,
      opponentAbbrev: "COL",
      pim: 0,
      toi: "59:45",
    },
    {
      gameId: 2024020201,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-11-05",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Utah Hockey Club",
        fr: "Club de hockey de l'Utah",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 21,
      goalsAgainst: 0,
      savePctg: 1,
      shutouts: 1,
      opponentAbbrev: "UTA",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020186,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-11-03",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Lightning",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 30,
      goalsAgainst: 4,
      savePctg: 0.866667,
      shutouts: 0,
      opponentAbbrev: "TBL",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020156,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-10-30",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Red Wings",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 21,
      goalsAgainst: 2,
      savePctg: 0.904762,
      shutouts: 0,
      opponentAbbrev: "DET",
      pim: 0,
      toi: "60:00",
    },
    {
      gameId: 2024020143,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-10-28",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Maple Leafs",
      },
      gamesStarted: 1,
      decision: "L",
      shotsAgainst: 35,
      goalsAgainst: 5,
      savePctg: 0.857143,
      shutouts: 0,
      opponentAbbrev: "TOR",
      pim: 0,
      toi: "59:21",
    },
    {
      gameId: 2024020116,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-10-24",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Kraken",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 32,
      goalsAgainst: 3,
      savePctg: 0.90625,
      shutouts: 0,
      opponentAbbrev: "SEA",
      pim: 0,
      toi: "61:19",
    },
    {
      gameId: 2024020099,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-10-22",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Blues",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 29,
      goalsAgainst: 2,
      savePctg: 0.931034,
      shutouts: 0,
      opponentAbbrev: "STL",
      pim: 0,
      toi: "59:25",
    },
    {
      gameId: 2024020073,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-10-18",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Sharks",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 22,
      goalsAgainst: 3,
      savePctg: 0.863636,
      shutouts: 0,
      opponentAbbrev: "SJS",
      pim: 0,
      toi: "59:16",
    },
    {
      gameId: 2024020038,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-10-13",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Wild",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 27,
      goalsAgainst: 1,
      savePctg: 0.962963,
      shutouts: 0,
      opponentAbbrev: "MIN",
      pim: 0,
      toi: "60:50",
    },
    {
      gameId: 2024020021,
      teamAbbrev: "WPG",
      homeRoadFlag: "H",
      gameDate: "2024-10-11",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Blackhawks",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 26,
      goalsAgainst: 1,
      savePctg: 0.961538,
      shutouts: 0,
      opponentAbbrev: "CHI",
      pim: 0,
      toi: "60:04",
    },
    {
      gameId: 2024020008,
      teamAbbrev: "WPG",
      homeRoadFlag: "R",
      gameDate: "2024-10-09",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Jets",
      },
      opponentCommonName: {
        default: "Oilers",
      },
      gamesStarted: 1,
      decision: "W",
      shotsAgainst: 30,
      goalsAgainst: 0,
      savePctg: 1,
      shutouts: 1,
      opponentAbbrev: "EDM",
      pim: 0,
      toi: "60:00",
    },
  ],
};
